# Generated by Django 2.2 on 2020-11-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='golongan_darah',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
    ]
