# Generated by Django 2.2 on 2020-11-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='no_kamar',
            new_name='profil',
        ),
    ]
